package com.insa.education.enums;

public enum RequestStatus {
    PENDING_DEPARTMENT_SUBMISSION,
    SUBMITTED_TO_CENTER,
    CENTER_REVIEWED,
    FORWARDED_TO_HR,
    HR_VERIFIED,
    SCORED,
    COMMITTEE_REVIEW,
    APPROVED,
    REJECTED,
    CONTRACT_CREATED
}
