spring.application.name=training-module
server.port=8082

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/training_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Keycloak Configuration (OAuth2 Resource Server)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/erp-system
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/erp-system/protocol/openid-connect/certs

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.com.insa.training=DEBUG
